version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install @cypress/commit-message-install
      - run: |
          if ! $(npm bin)/has-message; then
            echo Stopping early, no commit message
            circleci-agent step halt
          else
            echo All good, found commit message JSON
          fi
      - run: echo "After check"

  after-build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run: Echo After build

workflows:
  big:
    jobs:
      - build
      - after-build:
          requires:
            - build
